import express, { type Request, type Response } from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { env, realMoneyGate } from './config/env.js';
import system from './modules/system.js';
import auth from './modules/auth.js';
import kyc from './modules/kyc.js';
import wallet from './modules/wallet.js';
import payments from './modules/payments.js';
import sports from './modules/sports.js';
import casino from './modules/casino.js';
import responsible from './modules/responsible.js';
import admin from './modules/admin.js';
import { errorHandler, notFound } from './middleware/errors.js';

const app=express();
app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:env.FRONTEND_URL,credentials:true}));
app.use(rateLimit({windowMs:60_000,limit:180,standardHeaders:'draft-7',legacyHeaders:false}));
app.use(cookieParser());
app.use(express.json({limit:'1mb'}));
app.get('/',(_q:Request,res:Response)=>res.json({name:env.BRAND_NAME,version:'3.0.0',productionGate:realMoneyGate()}));
app.use('/api/system',system);
app.use('/api/auth',auth);
app.use('/api/kyc',kyc);
app.use('/api/wallet',wallet);
app.use('/api/payments',payments);
app.use('/api/sports',sports);
app.use('/api/casino',casino);
app.use('/api/responsible',responsible);
app.use('/api/admin',admin);
app.use(notFound);
app.use(errorHandler);
app.listen(env.API_PORT,()=>console.log('api_started',{port:env.API_PORT,brand:env.BRAND_NAME,realMoney:realMoneyGate().enabled}));
