import { Router } from 'express';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { pool, tx } from '../config/db.js';
import { env } from '../config/env.js';
import { asyncRoute, HttpError } from '../middleware/errors.js';
import { hashCpf, hashToken, randomToken } from '../utils/security.js';
import { requireAuth } from '../middleware/auth.js';
const r=Router();
const register=z.object({email:z.string().email(),phone:z.string().min(8),password:z.string().min(10),fullName:z.string().min(3),birthDate:z.string().date(),cpf:z.string().min(11)});
const login=z.object({email:z.string().email(),password:z.string().min(1)});
function age(date:string){const d=new Date(date+'T00:00:00Z');const n=new Date();let a=n.getUTCFullYear()-d.getUTCFullYear();const m=n.getUTCMonth()-d.getUTCMonth();if(m<0||(m===0&&n.getUTCDate()<d.getUTCDate()))a--;return a;}
function access(user:{id:string;email:string;role:string}){return jwt.sign({sub:user.id,email:user.email,role:user.role},env.JWT_ACCESS_SECRET,{expiresIn:env.JWT_ACCESS_EXPIRES_IN as any});}
const cookieOpts={httpOnly:true,secure:env.NODE_ENV==='production',sameSite:'lax' as const,path:'/api/auth',maxAge:env.JWT_REFRESH_EXPIRES_DAYS*86400000};
async function issueRefresh(c:any,userId:string,req:any){const token=randomToken();const expires=new Date(Date.now()+env.JWT_REFRESH_EXPIRES_DAYS*86400000);await c.query('insert into refresh_sessions(user_id,token_hash,user_agent,ip,expires_at) values($1,$2,$3,$4,$5)',[userId,hashToken(token),req.headers['user-agent']||null,req.ip||null,expires]);return token;}
r.post('/register',asyncRoute(async(req,res)=>{const b=register.parse(req.body);if(age(b.birthDate)<18)throw new HttpError(400,'Cadastro permitido somente para maiores de 18 anos.','underage');const out=await tx(async c=>{const h=await bcrypt.hash(b.password,12);const q=await c.query('insert into users(email,phone,password_hash,full_name,birth_date,cpf_hash) values($1,$2,$3,$4,$5,$6) returning id,email,role,status,kyc_status',[b.email.toLowerCase(),b.phone,h,b.fullName,b.birthDate,hashCpf(b.cpf)]);await c.query('insert into wallets(user_id) values($1)',[q.rows[0].id]);await c.query('insert into responsible_limits(user_id,max_stake,daily_deposit_limit,weekly_deposit_limit) values($1,1000,5000,15000)',[q.rows[0].id]);return q.rows[0];});res.status(201).json(out);}));
r.post('/login',asyncRoute(async(req,res)=>{const b=login.parse(req.body);const q=await pool.query('select id,email,role,status,password_hash,kyc_status from users where email=$1',[b.email.toLowerCase()]);const u=q.rows[0];if(!u||!(await bcrypt.compare(b.password,u.password_hash)))throw new HttpError(401,'Credenciais inválidas.','invalid_credentials');if(['banned','suspended'].includes(u.status))throw new HttpError(403,'Conta indisponível.','account_blocked');const refresh=await tx(c=>issueRefresh(c,u.id,req));res.cookie('refresh_token',refresh,cookieOpts);res.json({accessToken:access(u),user:{id:u.id,email:u.email,role:u.role,status:u.status,kycStatus:u.kyc_status}});}));
r.post('/refresh',asyncRoute(async(req,res)=>{const token=String(req.cookies?.refresh_token||'');if(!token)throw new HttpError(401,'Refresh token obrigatório.','invalid_refresh');const out=await tx(async c=>{const q=await c.query('select rs.id,rs.user_id,u.email,u.role,u.status from refresh_sessions rs join users u on u.id=rs.user_id where rs.token_hash=$1 and rs.revoked_at is null and rs.expires_at>now() for update',[hashToken(token)]);const s=q.rows[0];if(!s)throw new HttpError(401,'Sessão expirada.','invalid_refresh');await c.query('update refresh_sessions set revoked_at=now() where id=$1',[s.id]);const newRefresh=await issueRefresh(c,s.user_id,req);return{accessToken:access({id:s.user_id,email:s.email,role:s.role}),newRefresh};});res.cookie('refresh_token',out.newRefresh,cookieOpts);res.json({accessToken:out.accessToken});}));
r.post('/logout',asyncRoute(async(req,res)=>{const token=String(req.cookies?.refresh_token||'');if(token)await pool.query('update refresh_sessions set revoked_at=now() where token_hash=$1',[hashToken(token)]);res.clearCookie('refresh_token',{path:'/api/auth'});res.status(204).end();}));
r.get('/me',requireAuth,asyncRoute(async(req,res)=>{const q=await pool.query('select id,email,phone,full_name,birth_date,role,status,kyc_status,created_at from users where id=$1',[req.user!.sub]);res.json(q.rows[0]);}));
export default r;
