import { Router } from 'express';
import crypto from 'node:crypto';
import { pool, tx } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncRoute, HttpError } from '../middleware/errors.js';
import { casinoProvider } from '../services/providers.js';
import { env, realMoneyGate } from '../config/env.js';
import { credit } from './wallet.js';
import { assertCanPlay } from './responsible.js';
import { casinoCatalog } from '../data/casinoCatalog.js';
const r=Router();
function providerReady(){return Boolean(env.CASINO_PROVIDER_BASE_URL&&env.CASINO_PROVIDER_API_KEY)}
function normalizeGame(g:any,launchEnabled=providerReady()){return{provider_game_id:String(g.provider_game_id||g.game_id||g.id||''),name:String(g.name||g.title||''),provider:String(g.provider||g.provider_name||g.provider_payload?.provider||'Provedor'),category:String(g.category||'casino'),thumbnail_url:g.thumbnail_url||g.thumbnail||g.image||null,is_active:g.is_active!==false,launch_enabled:launchEnabled}}
r.get('/games',asyncRoute(async(_req,res)=>{const cached=await pool.query("select provider_game_id,name,category,thumbnail_url,is_active,provider_payload from casino_games where is_active=true order by name limit 300");if(cached.rowCount)return res.json(cached.rows.map(g=>normalizeGame(g)));if(!providerReady())return res.json(casinoCatalog.map(g=>normalizeGame({...g,provider_game_id:g.id},false)));const data=await casinoProvider.listGames();res.json((Array.isArray(data)?data:data?.games||[]).map((g:any)=>normalizeGame(g,true)));}));
r.post('/sync',asyncRoute(async(req,res)=>{if(String(req.headers['x-internal-secret']||'')!==env.INTERNAL_JOB_SECRET)throw new HttpError(401,'Não autorizado.');if(!providerReady())throw new HttpError(503,'Credencial do agregador de cassino pendente.','provider_not_configured');const raw=await casinoProvider.listGames();const games=Array.isArray(raw)?raw:raw?.games||[];let count=0;for(const g of games as any[]){const n=normalizeGame(g,true);if(!n.provider_game_id||!n.name)continue;await pool.query(`insert into casino_games(provider_game_id,name,category,thumbnail_url,is_active,provider_payload) values($1,$2,$3,$4,true,$5) on conflict(provider_game_id) do update set name=excluded.name,category=excluded.category,thumbnail_url=excluded.thumbnail_url,is_active=true,provider_payload=excluded.provider_payload,updated_at=now()`,[n.provider_game_id,n.name,n.category,n.thumbnail_url,{...g,provider:n.provider}]);count++;}res.json({ok:true,count});}));
r.post('/launch',requireAuth,asyncRoute(async(req,res)=>{const gameId=String(req.body?.gameId||'').trim();if(!gameId)throw new HttpError(400,'Jogo obrigatório.','game_required');if(!realMoneyGate().enabled)throw new HttpError(503,'Cassino real aguarda licença e credenciais de produção.','production_not_ready');if(!providerReady())throw new HttpError(503,'Credencial do agregador de cassino pendente.','provider_not_configured');await assertCanPlay(req.user!.sub,req.user!.sessionStart);const game=(await pool.query('select provider_game_id,is_active from casino_games where provider_game_id=$1',[gameId])).rows[0];if(game&&game.is_active===false)throw new HttpError(404,'Jogo indisponível.','game_unavailable');const p=await casinoProvider.launch({userId:req.user!.sub,gameId,returnUrl:`${env.FRONTEND_URL}/casino`});const sessionId=String(p.session_id||p.id||'');const url=p.url||p.launch_url||null;if(!url)throw new HttpError(502,'Provedor não retornou URL de lançamento.','provider_launch_invalid');await pool.query('insert into casino_sessions(user_id,provider_game_id,provider_session_id,status) values($1,$2,$3,$4)',[req.user!.sub,gameId,sessionId,'active']);res.status(201).json({url,sessionId});}));
r.post('/callback',asyncRoute(async(req,res)=>{if(!env.CASINO_CALLBACK_SECRET)throw new HttpError(503,'Callback de cassino não configurado.');const signature=String(req.headers['x-casino-signature']||'');const raw=JSON.stringify(req.body||{});const expected=crypto.createHmac('sha256',env.CASINO_CALLBACK_SECRET).update(raw).digest('hex');if(signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))throw new HttpError(401,'Assinatura inválida.');const eventId=String(req.body?.event_id||req.body?.id||'');const userId=String(req.body?.user_id||'');const delta=Number(req.body?.wallet_delta||0);if(!eventId||!userId||!Number.isFinite(delta))throw new HttpError(400,'Callback inválido.');await tx(async c=>{const i=await c.query('insert into webhook_events(provider,event_key,payload) values($1,$2,$3) on conflict(event_key) do nothing returning id',['casino',`casino:${eventId}`,req.body]);if(!i.rowCount)return;await credit(c,userId,delta,'casino',`casino:${eventId}`,`casino:${eventId}`);});res.json({ok:true});}));
export default r;
