import { Router } from 'express';
import crypto from 'node:crypto';
import { env, providerStatus } from '../config/env.js';
import { pool } from '../config/db.js';
import { requireAuth, type AuthRequest } from '../middleware/auth.js';
const r=Router();
r.post('/start',requireAuth,async(req:AuthRequest,res)=>{if(!providerStatus().kyc)return res.status(503).json({error:'kyc_provider_not_configured'});const reference=crypto.randomUUID();const response=await fetch(`${env.KYC_PROVIDER_BASE_URL}/cases`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${env.KYC_PROVIDER_API_KEY}`},body:JSON.stringify({external_reference:reference,user_id:req.user!.id,callback_url:`${env.PUBLIC_DOMAIN}/api/kyc/callback`})});if(!response.ok)return res.status(502).json({error:'kyc_provider_error'});const data:any=await response.json();await pool.query(`INSERT INTO kyc_cases(user_id,provider,provider_case_id,status,created_at) VALUES($1,$2,$3,'pending',now())`,[req.user!.id,env.KYC_PROVIDER,data.id]);await pool.query(`UPDATE users SET kyc_status='pending' WHERE id=$1`,[req.user!.id]);res.status(201).json({caseId:data.id,url:data.url||null,status:'pending'});});
r.post('/callback',async(req,res)=>{if(env.KYC_CALLBACK_SECRET&&req.get('x-callback-secret')!==env.KYC_CALLBACK_SECRET)return res.status(401).end();const id=String(req.body?.id||''),status=String(req.body?.status||'').toLowerCase();const mapped=['approved','rejected'].includes(status)?status:'pending';const q=await pool.query(`UPDATE kyc_cases SET status=$1,updated_at=now() WHERE provider_case_id=$2 RETURNING user_id`,[mapped,id]);if(q.rowCount&&mapped==='approved')await pool.query(`UPDATE users SET kyc_status='approved',status='active',role='verified',updated_at=now() WHERE id=$1`,[q.rows[0].user_id]);if(q.rowCount&&mapped==='rejected')await pool.query(`UPDATE users SET kyc_status='rejected',updated_at=now() WHERE id=$1`,[q.rows[0].user_id]);res.json({ok:true});});
export default r;
