import { Router } from 'express';
import crypto from 'node:crypto';
import { env, providerStatus } from '../config/env.js';
import { pool, tx } from '../config/db.js';
import { requireAuth, type AuthRequest } from '../middleware/auth.js';
const r=Router();
r.post('/pix',requireAuth,async(req:AuthRequest,res)=>{if(!providerStatus().payments)return res.status(503).json({error:'payment_provider_not_configured'});const amount=Number(req.body?.amount);if(!Number.isFinite(amount)||amount<env.MIN_DEPOSIT_BRL)return res.status(400).json({error:'invalid_deposit_amount'});const u=await pool.query(`SELECT email,status FROM users WHERE id=$1`,[req.user!.id]);if(!u.rowCount||u.rows[0].status==='banned')return res.status(403).json({error:'account_restricted'});const limits=await pool.query(`SELECT daily_deposit_limit,weekly_deposit_limit,self_excluded_until FROM responsible_limits WHERE user_id=$1`,[req.user!.id]);if(limits.rows[0]?.self_excluded_until&&new Date(limits.rows[0].self_excluded_until)>new Date())return res.status(403).json({error:'self_excluded'});const sums=await pool.query(`SELECT coalesce(sum(amount) FILTER(WHERE approved_at>=date_trunc('day',now())),0) day,coalesce(sum(amount) FILTER(WHERE approved_at>=date_trunc('week',now())),0) week FROM deposits WHERE user_id=$1 AND status='approved'`,[req.user!.id]);if(Number(sums.rows[0].day)+amount>Number(limits.rows[0].daily_deposit_limit))return res.status(400).json({error:'daily_deposit_limit'});if(Number(sums.rows[0].week)+amount>Number(limits.rows[0].weekly_deposit_limit))return res.status(400).json({error:'weekly_deposit_limit'});const id=crypto.randomUUID();const response=await fetch('https://api.mercadopago.com/v1/payments',{method:'POST',headers:{'authorization':`Bearer ${env.MERCADOPAGO_ACCESS_TOKEN}`,'content-type':'application/json','x-idempotency-key':id},body:JSON.stringify({transaction_amount:amount,description:`Depósito ${env.BRAND_NAME}`,payment_method_id:'pix',external_reference:id,payer:{email:u.rows[0].email},notification_url:env.PAYMENT_WEBHOOK_URL})});const data:any=await response.json();if(!response.ok)return res.status(502).json({error:'payment_provider_error',providerMessage:data?.message});await pool.query(`INSERT INTO deposits(id,user_id,provider,provider_payment_id,amount,status) VALUES($1,$2,'mercadopago',$3,$4,'pending')`,[id,req.user!.id,String(data.id),amount]);res.status(201).json({id,status:data.status,qrCode:data.point_of_interaction?.transaction_data?.qr_code||null,qrCodeBase64:data.point_of_interaction?.transaction_data?.qr_code_base64||null});});
r.post('/webhook/mercadopago',async(req,res)=>{if(!providerStatus().payments)return res.status(503).end();const paymentId=String(req.body?.data?.id||req.query['data.id']||'');if(!paymentId)return res.json({ok:true});const response=await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{'authorization':`Bearer ${env.MERCADOPAGO_ACCESS_TOKEN}`}});if(!response.ok)return res.status(202).json({ok:false});const p:any=await response.json();const deposit=await pool.query(`SELECT * FROM deposits WHERE provider='mercadopago' AND provider_payment_id=$1`,[paymentId]);if(!deposit.rowCount)return res.json({ok:true});const d=deposit.rows[0];if(String(p.external_reference)!==d.id||Number(p.transaction_amount)!==Number(d.amount))return res.status(409).json({error:'provider_data_mismatch'});if(p.status==='approved'){await tx(async c=>{const locked=await c.query(`SELECT * FROM deposits WHERE id=$1 FOR UPDATE`,[d.id]);if(locked.rows[0].status==='approved')return;const w=await c.query(`SELECT * FROM wallets WHERE user_id=$1 FOR UPDATE`,[d.user_id]);await c.query(`UPDATE wallets SET balance=balance+$1,updated_at=now() WHERE id=$2`,[d.amount,w.rows[0].id]);await c.query(`UPDATE deposits SET status='approved',approved_at=now() WHERE id=$1`,[d.id]);await c.query(`INSERT INTO ledger(wallet_id,kind,amount,reference,idempotency_key,status) VALUES($1,'deposit',$2,$3,$4,'completed')`,[w.rows[0].id,d.amount,d.id,`deposit:${d.id}`]);});}res.json({ok:true});});
export default r;
