import { Router } from 'express';
import { z } from 'zod';
import { pool } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncRoute, HttpError } from '../middleware/errors.js';
const r=Router();
r.get('/',requireAuth,asyncRoute(async(req,res)=>{const q=await pool.query('select * from responsible_limits where user_id=$1',[req.user!.sub]);res.json(q.rows[0]);}));
r.put('/limits',requireAuth,asyncRoute(async(req,res)=>{const s=z.object({maxStake:z.coerce.number().positive(),dailyDepositLimit:z.coerce.number().nonnegative(),weeklyDepositLimit:z.coerce.number().nonnegative(),sessionTimeLimitMin:z.coerce.number().int().min(15).max(1440).optional()}).parse(req.body);await pool.query('update responsible_limits set max_stake=$1,daily_deposit_limit=$2,weekly_deposit_limit=$3,session_time_limit_min=$4,updated_at=now() where user_id=$5',[s.maxStake,s.dailyDepositLimit,s.weeklyDepositLimit,s.sessionTimeLimitMin||null,req.user!.sub]);res.json({ok:true});}));
r.post('/self-exclusion',requireAuth,asyncRoute(async(req,res)=>{const p=z.object({period:z.enum(['24h','7d','30d','permanent'])}).parse(req.body);const days:Record<'24h'|'7d'|'30d',number>={'24h':1,'7d':7,'30d':30};const until=p.period==='permanent'?null:new Date(Date.now()+days[p.period as keyof typeof days]*86400000);await pool.query('update responsible_limits set self_excluded_until=$1,permanent_self_exclusion=$2,updated_at=now() where user_id=$3',[until,p.period==='permanent',req.user!.sub]);await pool.query("update users set status='self_excluded',updated_at=now() where id=$1",[req.user!.sub]);res.json({ok:true,until,permanent:p.period==='permanent'});}));
export async function assertCanBet(userId:string,stake:number){const q=(await pool.query('select u.status,u.kyc_status,l.max_stake,l.self_excluded_until,l.permanent_self_exclusion from users u join responsible_limits l on l.user_id=u.id where u.id=$1',[userId])).rows[0];if(!q)throw new HttpError(404,'Usuário não encontrado.');if(q.kyc_status!=='approved'||q.status!=='active')throw new HttpError(403,'Conta não está liberada para apostar.','account_not_active');if(q.permanent_self_exclusion||(q.self_excluded_until&&new Date(q.self_excluded_until)>new Date()))throw new HttpError(403,'Autoexclusão ativa.','self_excluded');if(stake>Number(q.max_stake))throw new HttpError(400,'Valor acima do limite pessoal por aposta.','stake_limit');}
export default r;
