import { Router } from 'express';
import { z } from 'zod';
import { pool, tx } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncRoute, HttpError } from '../middleware/errors.js';
import { sportsProvider } from '../services/providers.js';
import { assertCanBet } from './responsible.js';
import { holdStake, settleStake } from './wallet.js';
import { env, realMoneyGate } from '../config/env.js';
const r=Router();
function internal(req:any){if(String(req.headers['x-internal-secret']||'')!==env.INTERNAL_JOB_SECRET)throw new HttpError(401,'Não autorizado.');}
function scoreOf(item:any,team:string){const s=(item.scores||[]).find((x:any)=>String(x.name||'').toLowerCase()===team.toLowerCase());const n=Number(s?.score);return Number.isFinite(n)?n:null}
function settleResult(b:any,home:number,away:number):'won'|'lost'|'void'{const key=String(b.market_key||'').toLowerCase(),selection=String(b.selection||'').toLowerCase();if(key==='h2h'){const winner=home===away?'draw':home>away?String(b.home_team).toLowerCase():String(b.away_team).toLowerCase();return selection===winner?'won':'lost'}if(key==='totals'){const point=Number(b.point);if(!Number.isFinite(point))return'void';const total=home+away;if(total===point)return'void';if(selection.includes('over'))return total>point?'won':'lost';if(selection.includes('under'))return total<point?'won':'lost'}return'void'}
r.get('/events',asyncRoute(async(req,res)=>{const live=String(req.query.live||'false')==='true';const q=await pool.query(`select e.id,e.external_id,e.sport_key,e.sport_title,e.home_team,e.away_team,e.commence_time,e.status,coalesce(json_agg(json_build_object('id',m.id,'marketKey',m.market_key,'selection',m.selection,'point',m.point,'odds',m.odds,'isOpen',m.is_open) order by m.market_key,m.selection) filter(where m.id is not null),'[]') markets from sports_events e left join sports_markets m on m.event_id=e.id where e.commence_time>now()-interval '6 hours' ${live?"and e.status='live'":""} group by e.id order by e.commence_time limit 100`);res.json(q.rows);}));
r.post('/sync',asyncRoute(async(req,res)=>{internal(req);const sport=String(req.body?.sportKey||'soccer_brazil_campeonato');const data=await sportsProvider.listOdds(sport);let events=0,markets=0;await tx(async c=>{for(const event of data as any[]){const e=(await c.query(`insert into sports_events(external_id,sport_key,sport_title,home_team,away_team,commence_time,status,provider_payload) values($1,$2,$3,$4,$5,$6,'scheduled',$7) on conflict(external_id) do update set sport_key=excluded.sport_key,sport_title=excluded.sport_title,home_team=excluded.home_team,away_team=excluded.away_team,commence_time=excluded.commence_time,provider_payload=excluded.provider_payload,updated_at=now() returning id`,[event.id,sport,event.sport_title||sport,event.home_team,event.away_team,event.commence_time,event])).rows[0];events++;for(const bookmaker of event.bookmakers||[]){for(const market of bookmaker.markets||[]){for(const outcome of market.outcomes||[]){await c.query(`insert into sports_markets(event_id,market_key,selection,point,odds,source,is_open) values($1,$2,$3,$4,$5,$6,true) on conflict(event_id,market_key,selection,point_key) do update set odds=excluded.odds,source=excluded.source,is_open=true,updated_at=now()`,[e.id,market.key,outcome.name,outcome.point??null,outcome.price,bookmaker.key]);markets++;}}}}});res.json({ok:true,events,markets});}));
r.post('/results/sync',asyncRoute(async(req,res)=>{internal(req);const sport=String(req.body?.sportKey||'soccer_brazil_campeonato');const raw=await sportsProvider.listScores(sport);const scores=Array.isArray(raw)?raw:raw?.scores||[];let finished=0,settled=0;for(const item of scores as any[]){if(item.completed!==true&&String(item.status||'').toLowerCase()!=='completed'&&String(item.status||'').toLowerCase()!=='finished')continue;const event=(await pool.query('select * from sports_events where external_id=$1',[String(item.id)])).rows[0];if(!event)continue;const home=scoreOf(item,event.home_team),away=scoreOf(item,event.away_team);if(home===null||away===null)continue;await tx(async c=>{await c.query("update sports_events set status='finished',home_score=$1,away_score=$2,provider_payload=coalesce(provider_payload,'{}'::jsonb)||$3::jsonb,updated_at=now() where id=$4",[home,away,JSON.stringify({score_result:item}),event.id]);await c.query('update sports_markets set is_open=false,updated_at=now() where event_id=$1',[event.id]);const bets=await c.query(`select b.*,m.market_key,m.selection,m.point,e.home_team,e.away_team from sports_bets b join sports_markets m on m.id=b.market_id join sports_events e on e.id=m.event_id where m.event_id=$1 and b.status='open' for update of b`,[event.id]);for(const b of bets.rows){const result=settleResult(b,home,away);const payout=result==='won'?Number(b.potential_payout):result==='void'?Number(b.stake):0;await settleStake(c,b.user_id,Number(b.stake),payout,`sports_bet:${b.id}`,`settlement:${b.id}`);await c.query('update sports_bets set status=$1,settled_at=now() where id=$2',[result,b.id]);settled++;}});finished++;}res.json({ok:true,finished,settled});}));
r.post('/bets',requireAuth,asyncRoute(async(req,res)=>{const b=z.object({marketId:z.string().uuid(),stake:z.coerce.number().positive(),acceptedOdds:z.coerce.number().gt(1),idempotencyKey:z.string().min(12)}).parse(req.body);if(!realMoneyGate().enabled)throw new HttpError(503,'Apostas reais aguardam licença e credenciais de produção.','production_not_ready');await assertCanBet(req.user!.sub,b.stake,req.user!.sessionStart);const result=await tx(async c=>{const m=(await c.query('select m.*,e.commence_time,e.status from sports_markets m join sports_events e on e.id=m.event_id where m.id=$1 for share',[b.marketId])).rows[0];if(!m||!m.is_open||['finished','cancelled'].includes(m.status)||new Date(m.commence_time)<=new Date())throw new HttpError(400,'Mercado fechado.','market_closed');if(Math.abs(Number(m.odds)-b.acceptedOdds)>0.001)throw new HttpError(409,'A odd mudou. Atualize o bilhete.','odds_changed');const exists=await c.query('select * from sports_bets where idempotency_key=$1',[b.idempotencyKey]);if(exists.rowCount)return exists.rows[0];const potential=Math.round(b.stake*Number(m.odds)*100)/100;const bet=(await c.query(`insert into sports_bets(user_id,market_id,stake,odds_at_bet,potential_payout,status,idempotency_key) values($1,$2,$3,$4,$5,'open',$6) returning *`,[req.user!.sub,b.marketId,b.stake,m.odds,potential,b.idempotencyKey])).rows[0];await holdStake(c,req.user!.sub,b.stake,`sports_bet:${bet.id}`,`bet_hold:${bet.id}`);return bet;});res.status(201).json(result);}));
r.get('/bets/me',requireAuth,asyncRoute(async(req,res)=>{const q=await pool.query(`select b.*,m.market_key,m.selection,m.point,e.home_team,e.away_team,e.commence_time from sports_bets b join sports_markets m on m.id=b.market_id join sports_events e on e.id=m.event_id where b.user_id=$1 order by b.created_at desc limit 100`,[req.user!.sub]);res.json(q.rows);}));
r.post('/bets/:id/settle',asyncRoute(async(req,res)=>{internal(req);const outcome=z.object({result:z.enum(['won','lost','void'])}).parse(req.body);const result=await tx(async c=>{const b=(await c.query('select * from sports_bets where id=$1 for update',[req.params.id])).rows[0];if(!b)throw new HttpError(404,'Aposta não encontrada.');if(b.status!=='open')return b;const payout=outcome.result==='won'?Number(b.potential_payout):outcome.result==='void'?Number(b.stake):0;await settleStake(c,b.user_id,Number(b.stake),payout,`sports_bet:${b.id}`,`settlement:${b.id}`);const q=await c.query("update sports_bets set status=$1,settled_at=now() where id=$2 returning *",[outcome.result,b.id]);return q.rows[0];});res.json(result);}));
export default r;
