import { Router } from 'express';
import crypto from 'node:crypto';
import { z } from 'zod';
import { env } from '../config/env.js';
import { pool, tx } from '../config/db.js';
import { requireAuth, type AuthRequest } from '../middleware/auth.js';
const r=Router(); const amountSchema=z.coerce.number().positive().max(1_000_000);
export async function walletSnapshot(userId:string){const q=await pool.query(`SELECT balance,held_balance,currency FROM wallets WHERE user_id=$1`,[userId]);return q.rows[0]}
export async function hold(userId:string,amount:number,reference:string){return tx(async c=>{const w=await c.query(`SELECT * FROM wallets WHERE user_id=$1 FOR UPDATE`,[userId]);if(!w.rowCount||Number(w.rows[0].balance)<amount)throw new Error('insufficient_balance');const lim=await c.query(`SELECT * FROM responsible_limits WHERE user_id=$1`,[userId]);if(lim.rows[0]?.self_excluded_until&&new Date(lim.rows[0].self_excluded_until)>new Date())throw new Error('self_excluded');if(amount>Number(lim.rows[0]?.max_stake||0))throw new Error('stake_limit_exceeded');await c.query(`UPDATE wallets SET balance=balance-$1,held_balance=held_balance+$1,updated_at=now() WHERE id=$2`,[amount,w.rows[0].id]);await c.query(`INSERT INTO ledger(wallet_id,kind,amount,reference,idempotency_key,status) VALUES($1,'bet_hold',$2,$3,$4,'completed')`,[w.rows[0].id,-amount,reference,`hold:${reference}`]);return true;});}
export async function settle(userId:string,stake:number,payout:number,reference:string){return tx(async c=>{const dup=await c.query(`SELECT 1 FROM ledger WHERE idempotency_key=$1`,[`settle:${reference}`]);if(dup.rowCount)return;const w=await c.query(`SELECT * FROM wallets WHERE user_id=$1 FOR UPDATE`,[userId]);if(!w.rowCount||Number(w.rows[0].held_balance)<stake)throw new Error('invalid_held_balance');await c.query(`UPDATE wallets SET held_balance=held_balance-$1,balance=balance+$2,updated_at=now() WHERE id=$3`,[stake,payout,w.rows[0].id]);await c.query(`INSERT INTO ledger(wallet_id,kind,amount,reference,idempotency_key,status) VALUES($1,'bet_settlement',$2,$3,$4,'completed')`,[w.rows[0].id,payout,reference,`settle:${reference}`]);});}
r.get('/',requireAuth,async(req:AuthRequest,res)=>res.json(await walletSnapshot(req.user!.id)));
r.get('/transactions',requireAuth,async(req:AuthRequest,res)=>{const q=await pool.query(`SELECT l.* FROM ledger l JOIN wallets w ON w.id=l.wallet_id WHERE w.user_id=$1 ORDER BY l.created_at DESC LIMIT 100`,[req.user!.id]);res.json(q.rows)});
r.post('/withdrawals',requireAuth,async(req:AuthRequest,res)=>{const amount=amountSchema.parse(req.body?.amount);if(amount<env.MIN_WITHDRAWAL_BRL)return res.status(400).json({error:'below_minimum_withdrawal'});const u=await pool.query(`SELECT kyc_status,status FROM users WHERE id=$1`,[req.user!.id]);if(u.rows[0]?.kyc_status!=='approved'||u.rows[0]?.status!=='active')return res.status(403).json({error:'kyc_required'});const id=crypto.randomUUID();try{await tx(async c=>{const w=await c.query(`SELECT * FROM wallets WHERE user_id=$1 FOR UPDATE`,[req.user!.id]);if(Number(w.rows[0].balance)<amount)throw new Error('insufficient_balance');await c.query(`UPDATE wallets SET balance=balance-$1,held_balance=held_balance+$1 WHERE id=$2`,[amount,w.rows[0].id]);await c.query(`INSERT INTO withdrawals(id,user_id,amount,status) VALUES($1,$2,$3,'pending_review')`,[id,req.user!.id,amount]);await c.query(`INSERT INTO ledger(wallet_id,kind,amount,reference,idempotency_key,status) VALUES($1,'withdrawal_hold',$2,$3,$4,'completed')`,[w.rows[0].id,-amount,id,`withdraw:${id}`]);});res.status(201).json({id,status:'pending_review'});}catch(e:any){res.status(400).json({error:e.message});}});
export default r;
