import { Router } from 'express';
import { pool } from '../config/db.js';
import { realMoneyGate } from '../config/env.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncRoute, HttpError } from '../middleware/errors.js';
const r=Router();
export async function credit(c:any,userId:string,amount:number,kind:string,ref:string,key:string){if((kind==='deposit'||kind==='casino')&&!realMoneyGate().enabled)throw new HttpError(503,'Crédito real bloqueado até a ativação completa do ambiente.','production_not_ready');const w=(await c.query('select * from wallets where user_id=$1 for update',[userId])).rows[0];if(!w)throw new HttpError(404,'Carteira não encontrada.');const exists=await c.query('select id from ledger where idempotency_key=$1',[key]);if(exists.rowCount)return w;const next=Number(w.balance)+amount;if(next<0)throw new HttpError(400,'Saldo insuficiente.','insufficient_balance');await c.query('update wallets set balance=$1,updated_at=now() where id=$2',[next,w.id]);await c.query('insert into ledger(wallet_id,kind,amount,balance_after,reference,idempotency_key,status) values($1,$2,$3,$4,$5,$6,$7)',[w.id,kind,amount,next,ref,key,'completed']);return{...w,balance:next};}
export async function holdStake(c:any,userId:string,amount:number,ref:string,key:string){const w=(await c.query('select * from wallets where user_id=$1 for update',[userId])).rows[0];if(!w)throw new HttpError(404,'Carteira não encontrada.');if(Number(w.balance)<amount)throw new HttpError(400,'Saldo insuficiente.','insufficient_balance');const exists=await c.query('select id from ledger where idempotency_key=$1',[key]);if(exists.rowCount)return w;const balance=Number(w.balance)-amount;const held=Number(w.held_balance)+amount;await c.query('update wallets set balance=$1,held_balance=$2,updated_at=now() where id=$3',[balance,held,w.id]);await c.query('insert into ledger(wallet_id,kind,amount,balance_after,reference,idempotency_key,status) values($1,$2,$3,$4,$5,$6,$7)',[w.id,'bet_hold',-amount,balance,ref,key,'completed']);return{...w,balance,held_balance:held};}
export async function settleStake(c:any,userId:string,stake:number,payout:number,ref:string,key:string){const w=(await c.query('select * from wallets where user_id=$1 for update',[userId])).rows[0];const exists=await c.query('select id from ledger where idempotency_key=$1',[key]);if(exists.rowCount)return w;const held=Math.max(0,Number(w.held_balance)-stake);const balance=Number(w.balance)+payout;await c.query('update wallets set balance=$1,held_balance=$2,updated_at=now() where id=$3',[balance,held,w.id]);await c.query('insert into ledger(wallet_id,kind,amount,balance_after,reference,idempotency_key,status) values($1,$2,$3,$4,$5,$6,$7)',[w.id,'bet_settlement',payout,balance,ref,key,'completed']);return{...w,balance,held_balance:held};}
r.get('/',requireAuth,asyncRoute(async(req,res)=>{const w=(await pool.query('select balance,held_balance,currency,updated_at from wallets where user_id=$1',[req.user!.sub])).rows[0];const l=await pool.query('select id,kind,amount,balance_after,reference,status,created_at from ledger where wallet_id=(select id from wallets where user_id=$1) order by created_at desc limit 100',[req.user!.sub]);res.json({wallet:w,ledger:l.rows});}));
r.get('/summary',requireAuth,asyncRoute(async(req,res)=>{const q=await pool.query("select coalesce(sum(case when kind='deposit' and created_at>=date_trunc('day',now()) then amount else 0 end),0) daily_deposits,coalesce(sum(case when kind='withdrawal_hold' and created_at>=date_trunc('day',now()) then -amount else 0 end),0) daily_withdrawals from ledger where wallet_id=(select id from wallets where user_id=$1)",[req.user!.sub]);res.json(q.rows[0]);}));
export default r;
